version: '3.8'

services:
  latexb0x:
    build:
      context: .
      dockerfile: Dockerfile  # For building the image 
    container_name: latexb0x
    ports:
      - "9001:9001"
    volumes:
      - .latexbox/latex_id_ed25519.pub:/root/.ssh/latex_id_ed25519.pub  # Link your public key
      - ~/Documents/latexb0x/:/root/latexb0x # Mount the directory for your working files (adjust the path as needed)
    restart: unless-stopped  # Restart policy
